### ISSUE TITLE
about “find4QuadCornerSubpix” used in opencv_circle pattern

### ISSUE THREAD

**Issue by saiwing** [MrIsland/Thesis_Reproduction1#1]
In opencv_circle_iterative.cpp, findCirclesGrid() followed by find4QuadCornerSubpix
I think "find4QuadCornerSubpix" is used to refine chessboard corner, but not circle pattern. I don't know if I am right.
If I comment "find4QuadCornerSubpix", iteration doesn't seem to improve reprojection error

**Comment by MrIsland** [comment]
Thank you very much for your question, and I apologize for not seeing your inquiry sooner due to my busy schedule.
This was indeed an oversight on my part. The find4QuadCornerSubpix() function in OpenCV optimizes corner detection based on image gradients, which is ineffective for circle patterns. This is because the area around the circle center has the same color, resulting in a gradient of zero. So you are right.

By the way, if you want to achieve lower reprojection error, you can use a circular pattern or markers(like CCTAG), which is a part of this repo that was not yet completed. Additionally, you can choose a state-of-the-art ellipse detection algorithm. Removing erroneous corner points when projecting the bird's-eye view can also effectively improve calibration accuracy, as outliers significantly affect the calibration algorithms in OpenCV.
